version: '3'

services:
  redis:
    image: "redis:6.2.5"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-network

  rate-limiter:
    build:
      context: .
      target: builder
    container_name: rate-limiter
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - rate-limiter-network
    command: ["./main"]

  rate-limiter-tests:
    build:
      context: .
      target: tester
    container_name: rate-limiter-tests
    depends_on:
      - redis
    networks:
      - rate-limiter-network
    command: ["go", "test", "./limiter", "-v"]

networks:
  rate-limiter-network:
    driver: bridge
